### PR TITLE
Fix segfault on setting encoding

### PR DESCRIPTION
**Pull request by f2404**

### CODE REVIEW

**Comment by ochosi** [comment]
Odd, I haven't noticed any segfaults on setting the encoding - any hints as to how to reproduce this?

**Comment by f2404** [comment]
The segfault is happening on my system (Arch Linux, GTK 3.20.6, vte 0.44.2) on setting any encoding from Terminal -> Set Encoding menu:
```
(xfce4-terminal:18391): Vte-CRITICAL **: gboolean vte_terminal_set_encoding(VteTerminal*, const char*, GError**): assertion 'error == NULL || *error == NULL' failed
Segmentation fault (core dumped)
```
It seems that newer vte versions require 'error' to be NULL - this is what I'm suggesting in this PR.

**Comment by ochosi** [comment]
On second thought, it seems like the error is not set to NULL by default in terminal_screen_set_encoding and this may be causing the segfault, correct? As it is currently, you're just ignoring any errors..?

**Comment by f2404** [comment]
No, the errors are not ignored since `vte_terminal_set_encoding` may return `false`; the only possible reaction on an error could be writing a log message which is already done.

The `GError **error` parameter looks superfluous here; and in fact `gnome-terminal` is passing `NULL` as well (see for example https://github.com/GNOME/gnome-terminal/blob/master/src/terminal-screen.c#L694).

**Comment by ochosi** [comment]
Alright, that makes sense. Pushed!

**Pull request closed without merging**
